version: "1"
services:
  reverseproxy:
    build:
      context: .
    image: bjoebstl/reverseproxy
  backend_user:
    build:
      context: ../../udagram-api-user
    image: bjoebstl/udagram-api-user
  backend_feed:
    build:
      context: ../../udagram-api-feed
    image: bjoebstl/udagram-api-feed
  frontend:
    build:
      context: ../../udagram-frontend
    image: bjoebstl/udacgram-frontend:local